name: zoraxy
services:
  main_app:
    cpu_shares: 50
    command: []
    container_name: Zoraxy
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - AUTORENEW=86400
      - DESEC_POLLING_INTERVAL=15
      - DESEC_PROPAGATION_TIMEOUT=900
      - DESEC_TTL=900
      - DOCKER=true
      - EARLYRENEW=30
      - FASTGEOIP=true
      - TZ=Africa/Johannesburg
      - ZEROTIER=false
    hostname: Zoraxy
    image: zoraxydocker/zoraxy:latest
    labels:
      icon: https://github.com/tobychui/zoraxy/raw/main/img/title.png
    ports:
      - target: 8000
        published: "8003"
        protocol: ""
      - target: 443
        published: "443"
        protocol: ""
      - target: 80
        published: "80"
        protocol: ""
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/zoraxy/config
        target: /opt/zoraxy/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://github.com/tobychui/zoraxy/raw/main/img/title.png
  index: /
  is_uncontrolled: false
  port_map: "8003"
  scheme: http
  store_app_id: zoraxy
  title:
    custom: Zoraxy
